name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            role-to-assume: arn:aws:iam::769338321636:role/Github
            aws-region: us-east-2

      - name: Terraform Init
        run: terraform init ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve ./terraform

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id EXOXS5WMNVOM0 --paths "/*"
