name: Update Terraform Infrastructure

on:
  push:
    branches:
      - main

jobs:
  update-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS SSO
        run: |
          aws sso configure
          aws sso login --profile clinamad

      - name: Use SSO-Generated Credentials
        run: |
          SSO_CREDENTIALS=$(aws sso get-role-credentials --profile clinamad --role-name MySSORole)
          export AWS_ACCESS_KEY_ID=$(echo $SSO_CREDENTIALS | jq -r '.roleCredentials.accessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $SSO_CREDENTIALS | jq -r '.roleCredentials.secretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $SSO_CREDENTIALS | jq -r '.roleCredentials.sessionToken')

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

